version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./reporting_service/reports:/app/reporting_service/reports
    environment:
      - PYTHONUNBUFFERED=1